config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
    get 'inicio' => 'avisos#suatela'
    resources :avisos do
        member do
            post:criar_aviso
        end
    end
    resources :pesquisa_avisos
    resources :encomendas
    resources :conversations do
    resources :messages
  end

  devise_for :users
  root to: 'conversations#index'

  root to: 'discussions#index'
  resources :discussions
  #route para discussão, falar com zé Olenscki caso tenha duvida

  root to: 'calendarios#index'
  resources :calendarios
  #route para criação eventos, falar com zé Rafael caso tenha duvida

end

app/models/aviso.rb
class Aviso < ApplicationRecord
    validates :texto, presence: true, uniqueness: true
end

app/models/calendario.rb
class Calendario < ApplicationRecord
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # Verifica se so existe uma conversa entre eles

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/controllers/User_controllers.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  private
  # Use callbacks to share common setup or constraints between
    actions.
  def set_user
    @user = User.nd(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the
    white list through.
  def user_params
    params.require(:user).permit(:email, :password, :
    password_conrmation)
  end
end

app/controllers/avisos_controller.rb
class AvisosController < ApplicationController
before_action :set_aviso, only: [:show, :edit, :update, :destroy]
  def index
      @avisos = Aviso.all
      redirect_to inicio_path
  end

  def show
      redirect_to inicio_path
  end

  def new
      @aviso = Aviso.new
  end

  def edit
      redirect_to inicio_path
  end

  def create
      @aviso = Aviso.new(aviso_params)
      if @aviso.save
          redirect_to inicio_path,  erros: @aviso.errors.messages
      else
          redirect_to inicio_path(:erros => @aviso.errors.messages)
      end
  end

  def criar_aviso
      @avisos = Aviso.all
      @aviso = Aviso.new
      @aviso.texto = params[:texto]
      @aviso.usuario_id = params[:usuario_id]
      if @aviso.save
          redirect_to inicio_path
      else
          redirect_to inicio_path(:erros => @aviso.errors.messages)
      end
  end

  def suatela
      if params[:erros]
          @erros=params[:erros]
      else
          @erros=''
      end
      @usuarios = User.all
      @aviso = Aviso.new
      @avisos = Aviso.all
      if params[:ident]=='1'
          if not(params[:texto].blank?)
              @avisos = @avisos.where("texto like ?","%#{params[:texto]}%")
          end
          if not(params[:nome].blank?)
              @avisos = @avisos.where("usuario_id in (?)", User.where("name like ?","%#{params[:nome]}%").ids)
          end
      end
      if params[:ident]=='2'
          if not(params[:texto].blank?)
              @avisos = @avisos.where("texto like ?","%#{params[:texto]}%")
          end
          if not(params[:autor].blank?)
              @avisos = @avisos.where("usuario_id in (?)", User.where("name like ?","%#{params[:autor]}%").ids)
          end
          if not(params[:apto].blank?)
              @avisos = @avisos.where("usuario_id in (?)", User.where("apartamento like ?","#{params[:apto]}").ids)
          end
          if not(params[:autor_id].blank?)
              @avisos = @avisos.where("usuario_id like ?","%#{params[:autor_id]}%")
          end
          if not(params[:funcao]=='0')
              @avisos = @avisos.where("usuario_id in (?)", User.where("funcao like ?","#{params[:funcao]}").ids)
          end
          if not(params[:datetime_inicio].blank?)
              @avisos = @avisos.where("created_at >= ?", params[:datetime_inicio])
          end
          if not(params[:datetime_fim].blank?)
              @avisos = @avisos.where("created_at <= ?", params[:datetime_fim])
          end
      end

      if params[:paginas].nil?
          @avisos = @avisos.paginate(:page => params[:page], :per_page => 10)
      else
          if params[:paginas] == -1
              @avisos = @avisos.paginate(:page => params[:page], :per_page => @avisos.count)
          else
              @avisos = @avisos.paginate(:page => params[:page], :per_page => params[:paginas])
          end
      end
  end

  # PATCH/PUT /avisos/1
  # PATCH/PUT /avisos/1.json
  def update
    respond_to do |format|
      if @aviso.update(aviso_params)
        format.html { redirect_to @aviso, notice: 'Aviso was successfully updated.' }
        format.json { render :show, status: :ok, location: @aviso }
      else
        format.html { render :edit }
        format.json { render json: @aviso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avisos/1
  # DELETE /avisos/1.json
  def destroy
    @aviso.destroy
    respond_to do |format|
      format.html { redirect_to inicio_path, notice: 'O Aviso foi apagado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aviso
      @aviso = Aviso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aviso_params
      params.require(:aviso).permit(:usuario_id, :texto)
    end
end

app/controllers/calendarios_controller.rb
class CalendariosController < ApplicationController
  before_action :set_calendario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /calendarios
  # GET /calendarios.json
  def index
    @calendarios = Calendario.all
  end

  # GET /calendarios/1
  # GET /calendarios/1.json
  def show
  end

  # GET /calendarios/new
  def new
    @calendario = Calendario.new
  end

  # GET /calendarios/1/edit
  def edit
  end

  # POST /calendarios
  # POST /calendarios.json
  def create
    @calendario = Calendario.new(calendario_params)

    respond_to do |format|
      if @calendario.save
        format.html { redirect_to @calendario, notice: 'Calendario was successfully created.' }
        format.json { render :show, status: :created, location: @calendario }
      else
        format.html { render :new }
        format.json { render json: @calendario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendarios/1
  # PATCH/PUT /calendarios/1.json
  def update
    respond_to do |format|
      if @calendario.update(calendario_params)
        format.html { redirect_to @calendario, notice: 'Calendario was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendario }
      else
        format.html { render :edit }
        format.json { render json: @calendario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendarios/1
  # DELETE /calendarios/1.json
  def destroy
    @calendario.destroy
    respond_to do |format|
      format.html { redirect_to calendarios_url, notice: 'Calendario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendario
      @calendario = Calendario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendario_params
      params.require(:calendario).permit(:name, :start_time, :end_time, :descricao)
    end
end

app/controllers/pesquisa_avisos_controller.rb
class PesquisaAvisosController < ApplicationController
    def index
    end
end

app/helpers/avisos_helper.rb
module AvisosHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/views/avisos/_form.html.erb
<%= form_with(model: aviso, local: true) do |form| %>
  <% if aviso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aviso.errors.count, "error") %> prohibited this aviso from being saved:</h2>

      <ul>
      <% aviso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.number_field :usuario_id, id: :aviso_usuario_id %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :aviso_usuario_id, rows: 6, cols: 100 %>
  </div>

  <div class="actions">
    <%= form.submit "Criar Aviso!" %>
  </div>
<% end %>

app/views/avisos/edit.html.erb
<h1>Editing Aviso</h1>

<%= render 'form', aviso: @aviso %>

<%= link_to 'Show', @aviso %> |
<%= link_to 'Back', avisos_path %>

app/views/avisos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avisos</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Texto</th>
      <th>Criado em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avisos.each do |aviso| %>
      <tr>
        <td><%= aviso.usuario_id %></td>
        <td><%= aviso.texto %></td>
        <td><%= aviso.created_at %></td>
        <td><%= link_to 'Show', aviso %></td>
        <td><%= link_to 'Edit', edit_aviso_path(aviso) %></td>
        <td><%= link_to 'Destroy', aviso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aviso', new_aviso_path %>

app/views/avisos/new.html.erb
<h1>New Aviso</h1>

<%= render 'form', aviso: @aviso %>

<%= link_to 'Back', avisos_path %>

app/views/avisos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @aviso.usuario_id %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @aviso.texto %>
</p>

<%= link_to 'Edit', edit_aviso_path(@aviso) %> |
<%= link_to 'Back', avisos_path %>

app/views/avisos/suatela.html.erb
<p id="notice"><%= notice %></p><br>
<%= link_to 'Voltar à Página Inicial', 'conversations#index' %>
<h2> Faça a sua pesquisa! </h2>
<%= form_tag(inicio_path ,:method => :get) do %>
    <%= text_field_tag 'texto', nil, size: 80, placeholder: 'Digite a sua pesquisa aqui...' %>
    <%= text_field_tag 'nome', nil, size: 20, placeholder: 'Autor' %>
    <%= hidden_field_tag 'ident', 1 %>
    <%= submit_tag "Pesquisar!" %>
<% end %>
Não está satisfeito? Tente a <%= link_to "Pesquisa Avançada", pesquisa_avisos_path %>
<h1>Nosso Quadro de Avisos do Condomínio</h1>

<table>
  <thead>
    <tr>
      <th>ID do autor</th>
      <th>Nome do autor</th>
      <th>Texto</th>
      <th>Criado em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avisos.order('created_at DESC').each do |aviso| %>
      <tr>
        <td><%= aviso.usuario_id %></td>
        <td><%= User.find_by(id: aviso.usuario_id).name %></td>
        <td><%= aviso.texto %></td>
        <td>
            <%#= aviso.created_at.in_time_zone("Brasilia") %>
            <% diff = DateTime.parse("#{DateTime.now}").to_time - DateTime.parse("#{aviso.created_at}").to_time %>
            <% horas = (diff / 3600).floor %>
            <% minutos = ((diff / 60) % 60).floor  %>
            <% segundos = (diff % 60).floor  %>
            <%= time_ago_in_words((horas.hours + minutos.minutes + segundos.seconds).ago) %>
            <%#= '%d:%02d:%02d' % [ diff / 3600, (diff / 60) % 60, diff % 60 ] %>
        </td>
        <% if false %> <%#FORMA INTELIGENTE DE COMENTAR%>
            <td><%= link_to 'Show', aviso %></td>
            <td><%= link_to 'Edit', edit_aviso_path(aviso) %></td>
        <% end %>
        <td>
            <% if User.find(current_user.id).funcao==3 %>
                <%= link_to 'Apagar', aviso, method: :delete, data: { confirm: 'Tem certeza?' } %>
            <% else %>
                <% if aviso.usuario_id==current_user.id %>
                    <%= link_to 'Apagar', aviso, method: :delete, data: { confirm: 'Tem certeza?' } %>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @avisos, :previous_label => '<<', :next_label => '>>' %>
<%= form_tag(inicio_path ,:method => :get) do %>
    <%= select_tag :paginas, options_for_select([["10", 10], ["20", 20], ["Todos", -1]]) %>
    <%= submit_tag "Filtrar" %>
<% end %>
<h1>Quer criar um aviso novo?</h1>
<%= form_tag(criar_aviso_aviso_path(1),:method => :post) do %>
    <%= hidden_field_tag 'usuario_id', current_user.id %>
    <%= text_area_tag :texto, nil, rows: 5, cols: 100 %>
    <%= submit_tag "Enviar Aviso!" %>
<% end %>
<% if not(params[:erros].nil?) %>
    <% params[:erros].each do |mah_oe| %>
        <br> <%= mah_oe[0] %> <%= mah_oe[1][0] %>
    <% end %>
<% end %>

app/views/calendarios/_form.html.erb
<%= form_for @calendario, :html => { :class => "form-horizontal calendario" } do |f| %>

  <% if @calendario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@calendario.errors.count, "error") %> prohibited this calendario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @calendario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <div class="col-lg-10">
    <%= f.text_field :name, id: :calendario_name %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :Início  %>
    <div class="col-lg-10">
    
    <%= f.datetime_select :start_time, id: :calendario_start_time %>
     
    </div>
    <%=f.error_span(:start_time) %>
  </div>
  <div class="form-group">
    <%= f.label :Fim %>
    <div class="col-lg-10">
    <%= f.datetime_select :end_time, id: :calendario_end_time %>
    </div>
    <%=f.error_span(:end_time) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                calendarios_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/calendarios/edit.html.erb
<%- model_class = Calendario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/calendarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendário de Eventos</h1>

<%= month_calendar events: @calendarios do |date, calendarios| %>
  <%= date.strftime("%d/%m/%Y") %>

  <% calendarios.each do |calendario| %>
    <div>
      <%= link_to calendario.name, calendario%> - <%= calendario.start_time.strftime("%I:%M")%> até <%= calendario.end_time.strftime("%I:%M")%>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
    <th>Nome  </th>
    <th>Dia de Início  </th>
    <th>Dia de Fim </th>
    <th> Hora de Início - </th>
    <th> Hora de Fim</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendarios.each do |calendario| %>
      <tr>
      
      <td><%= calendario.name %></td>
        <td><%= calendario.start_time.strftime("%d/%m/%Y") %>  -  </td>
        
        <td><%= calendario.end_time.strftime("%d/%m/%Y") %>  -  </td>
        
        <td><%= calendario.start_time.strftime("%I:%M") %> até às </td>
        
        <td><%= calendario.end_time.strftime("%I:%M") %>  </td>
        
      <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
                    calendario_path(calendario), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_calendario_path(calendario), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    calendario_path(calendario),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-xs btn-danger' %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Evento', new_calendario_path %>
<div>
<%= link_to 'Voltar à Página Inicial', 'conversations#index' %>
<div>

app/views/calendarios/new.html.erb
<%- model_class = Calendario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/calendarios/show.html.erb
<%- model_class = Calendario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @calendario.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Início) %>:</strong></dt>
  <dd><%= @calendario.start_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Fim) %>:</strong></dt>
  <dd><%= @calendario.end_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Descricao) %>:</strong></dt>
  <dd><%= @calendario.descricao %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              calendarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_calendario_path(@calendario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              calendario_path(@calendario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/conversations/index.html.erb
<%= link_to "Quadro de Avisos", inicio_path %>
<div class="columns">
  <div class="column is-3">
    <h3 class="title is-3">Usuários</h3>
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
      <div class="navbar-dropdown is-right">
       <%= link_to "Enviar mensagem para #{user.name}", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post" %>
      </div>
      <% end %>
    <% end %>
  </div>

  <div class="column is-7">
    <h3 class="title is-3">Conversas</h3>
    <% @conversations.each do |conversation| %>
      <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <% unless current_user.id == recipient %>
          <div class="columns">
            <div class="column">
              <div class="inline-block"><%= link_to "Conversa com #{recipient.name}", conversation_messages_path(conversation) %></div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="column is-3">
    <h3 class="title is-3">Encomendas</h3>
      <div class="navbar-dropdown is-right">
       <%= link_to "Mostrar minhas encomendas", encomendas_path %>
      </div>
  </div>

  <div class="column is-3">
    <h3 class="title is-3">Reclamações</h3>
      <div class="navbar-dropdown is-right">
        <%= link_to "Mostrar as Reclamações", discussions_path %>
      </div>
  </div>
</div>

<div class="column is-3">
    <h3 class="title is-3">Eventos</h3>
      <div class="navbar-dropdown is-right">
       <%= link_to "Marcar um evento", calendarios_path %>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= 'Condominium App' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

     <nav class="navbar is-link" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">

          <h1 class="title is-5 has-text-white"><%= 'Condominium App' %></h1>

        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>

          <div class="navbar-item">
            <div class="field is-grouped">              
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
                </div>
            </div>
          </div>
          <% else %>
          <div class="navbar-item">
            <div class="field is-grouped">
            </div>
          </div>
          <% end %>

      </div>
    </div>
  </nav>

  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>
  </body>
  
</html>

app/views/messages/index.html.erb
<h1 class="title is-4">Messagens com <%= @conversation.recipient.name %></h1>

<% if @over_ten %>
  <%= link_to "Show previous", '?m=all', class:'button is-link' %>
<% end %>

<section id="messages" class="mb4">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <article class="message is-dark">
        <div class="message-body">

          <div class="inline-block"><strong><%= user.name %></strong> <%= message.message_time %></div>
          <div class="block pt4">
            <div class="f4"><%= sanitize markdown_to_html(message.body) %></div>
          </div>
        </div>
      </article>
    <% end %>
  <% end %>
</section>

<%= form_for [@conversation, @message] do |f| %>
  <%= f.text_area :body, class: "textarea", placeholder: "Digite aqui sua mensagem" %>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div class="text-align-right">
    <%= f.submit "Send message", class: "button is-link is-large mt3" %>
  </div>
<% end %>

app/views/pesquisa_avisos/index.html.erb
<%= link_to 'Voltar à Página Inicial', 'conversations#index' %><br>
<h1>Pesquisa Avançada</h1>
<%= form_tag(inicio_path ,:method => :get) do %>

    <div class="">
        Pesquisar por <%= text_field_tag 'texto', nil, size: 50, placeholder: 'texto' %>
    </div>
    <br>
    <div class="">
        Cujo autor contém as letras <%= text_field_tag 'autor', nil, size: 10, placeholder: 'autor' %>, mora no apartamento <%= text_field_tag 'apto', nil, size: 10, placeholder: 'Apartamento'%> e tem ID <%= text_field_tag 'autor_id', nil, size: 10, placeholder: 'ID do autor'%>
    </div>
    <br>
    <div class="">
        E foi postada entre <%= date_field_tag(:datetime_inicio, nil)%> e <%= date_field_tag(:datetime_fim, nil)%>
    </div>
    <br>
    <div class="">
        Filtrar por função: <%= select_tag :funcao, options_for_select([["Todos", 0],["Condômino", 1], ["Funcionário", 2], ["Síndico", 3]]) %>
    </div>
    <br>
    <%= hidden_field_tag 'ident', 2 %>
    <%= submit_tag "Pesquisa Avançada" %>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>